### ISSUE TITLE
Weird pop up for Beeline and GrabShuttle app when launched

### ISSUE THREAD

**Issue by chuasweechin** [datagovsg/beeline-frontend#473] opened 2017-12-14 00:30 UTC
![image](https://user-images.githubusercontent.com/22762719/33969576-00f8426a-e0a9-11e7-88d9-3456a2655bce.png)

**Comment by xkjyeah** [comment] 2017-12-14 05:47
The new app build is missing the Cordova geolocation plugin

**Comment by chuasweechin** [comment] 2017-12-14 05:50
I have only saw the error on iOS devices. According to @shen-xujing , the issue do not happen for Android.
In this case, will it still be a Plugin issue?

**Comment by xkjyeah** [comment] 2017-12-14 06:12
Yes... Check that the iOS build has Cordova plugin geolocation

**Comment by chuasweechin** [comment] 2017-12-14 06:44
When i download the build from app store which is uploaded in Jun 17, the issue didn't happen. This issue happens to the (base + hotcode push) build. It only happen after the hot code push is triggered. 

In this case, it doesn't seems like a plugin problem though. Xujing mentioned that Android also have Cordova plugin geolocation.

**Comment by xkjyeah** [comment] 2017-12-14 14:50
This is all very familiar...

Probably also happens if you try to ask for the user's location *before*
the plugin is initialized? Could you check if you're possibly asking for
the location too soon after program start up?

**Comment by chuasweechin** [comment] 2018-01-04 03:36
Issue fixed in the latest hotcode push by Xujing when changing the navigation bar. We got no idea what happen.

**Comment by chuasweechin** [comment] 2018-02-01 14:49
The issue is back. Think we need to investigate this

**Comment by chuasweechin** [comment] 2018-02-01 14:50
I saw the pop up in beeline

**Comment by chuasweechin** [comment] 2018-02-01 14:51
Think this happen after Joel recent hotcode push for the search bar. It is written in the screenshot

**Comment by chuasweechin** [comment] 2018-02-01 14:52
![c803cfc1-0844-4035-90b6-2e223ff54ce0](https://user-images.githubusercontent.com/22762719/35684672-9bb76c5c-07a2-11e8-96e5-8fdd63a431df.png)

**Comment by xkjyeah** [comment] 2018-02-01 15:35
@joel you *must* ensure that any geolocation query takes place only after
the Cordova plugins have been loaded....

**Comment by LoneRifle** [comment] 2018-02-28 07:03
Where are we with this?

**Comment by joelchoo** [comment] 2018-02-28 07:13
@LoneRifle are you still encountering this? I couldn't reproduce at all and didn't change anything that does geolocation queries

**Comment by LoneRifle** [comment] 2018-02-28 07:25
I don't use iOS. Just trying to tidy up the GitHub issues

**Comment by joelchoo** [comment] 2018-02-28 07:27
Ok let's close this then.

**Closed by joelchoo** 2018-02-28 07:27 UTC
